#!/usr/bin/ruby -w

# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:

# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

found = 0
tn_start = 280

def getTriNum(num)
  return num * (num + 1) / 2
end

def getPentNum(num)
  return num * (3 * num - 1) / 2
end

def getHexNum(num)
  return num * (2 * num - 1)
end

while found < 2
  found = 0
  pn_start = 166
  hn_start = 144

  new_tri_num = getTriNum(tn_start)
  
  while getPentNum(pn_start) < new_tri_num
    pn_start += 1
  end
  found += 1 if getPentNum(pn_start) == new_tri_num
  
  while getHexNum(hn_start) < new_tri_num
    hn_start += 1
  end
  found += 1 if getHexNum(hn_start) == new_tri_num
  
  tn_start += 1  
end
puts new_tri_num
